debug: true
sql: true
http:
  prefork: true
  address: :4000

keys:
  private: ./keys/private.key
  public: ./keys/public.key
  secret: ./keys/secret.key

log:
  level: info

databases:
  mongo:
    uri: mongodb://localhost:27017
  sql:
    provider: postgres
    dsn: 'host=localhost user=malusev password=M@lusevd998 dbname=vaulguard timezone=UTC'

