sql: true # Set SQL as main secret storage, if this is set to false, mongodb uri is required
console: true # Console logging
debug: true # Debug enables PProf
locale: en # VaulGuard Server validation locale
memory:
  # Reports memory usage overtime to console
  # This works only if debug is turned on
  report: true
  sleep: 30s
databases:
  # Storage engines - SQL and NoSQL(Mongo)
  # There is not partial data storage support
  sql:
    provider: postgres # supported drivers - sqlite, postgres, mysql
    dsn: 'host=postgres user=postgres password=postgres dbname=vaulguard port=5432 sslmode=disable TimeZone=UTC'
  mongo:
    uri: mongodb://mongo:27017
  redis:
    addr: redis:6379
    password: ''
logging:
  level: info # supported logging - debug, info, warning, error
http:
  prefork: false
  address: 0.0.0.0:4000 # HTTP Address
  session:
    cookie: vaulguard_session
    provider: redis
    secure: false
    domain: ''
    samesite: Lax
    expiration: 12h
    gc: 1m
keys:
  # If Directory does not exist, vaulguard will try to create it along with keys
  # Watch out!!! If you lose keys or change directory key keys will be generated
  # and secrets will be lost
  private: ./keys/private.key # Path to EdDSA (Ed25519) private key
  public: ./keys/public.key # Path to EdDSA (Ed25519) public key
  secret: ./keys/secret.key # Path to XChaCha20Poly1305 secret key
