version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: debug
    volumes:
      - go:/go/pkg
      - ${PWD}/config.yml:/config.yml
      - .:/app
    networks:
      - vaulguard
    restart: unless-stopped
    depends_on:
      - postgres
      - mongo
      - redis
    links:
      - mongo
      - postgres
      - redis
    ports:
      - 4000:4000
      - 40000:40000
  mongo:
    image: mongo:4.4.0-bionic
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    networks:
      - vaulguard
    ports:
      - '27017:27017'
  postgres:
    image: postgres:12.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: vaulguard
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    networks:
      - vaulguard
    ports:
      - '5432:5432'
  redis:
    image: redis:6.0.6-alpine
    ports:
      - 6379:6379
    networks:
      - vaulguard
    restart: unless-stopped
volumes:
  postgres:
    driver: local
  mongo:
    driver: local
  go:
    driver: local

networks:
  vaulguard:
    driver: bridge
