version: '3.3'

services:
  mongo:
    image: mongo:4.4.0-bionic
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    networks:
      - vaulguard
    ports:
      - '27017:27017'
  db:
    image: postgres:12.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: vaulguard
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    networks:
      - vaulguard
    ports:
      - '5432:5432'
volumes:
  postgres:
  mongo:
  go:

networks:
  vaulguard:
    driver: bridge
