version: '3'
tasks:
  development:
    cmds:
      - go run .
    env:
      PORT: 4000
      STORE_SECRETS_IN_SQL: true
      MONGODB: mongodb://localhost:27017
      DATABASE_PROVIDER: '{{.DEV_PROVIDER}}'
      DATABASE_DSN: '{{.DEV_DB}}'
      APP_KEY: Ode1S8s63tz7Us5CIbJkjiI4GRWuQX2e9WKHeefCgHg=
