version: '3'
tasks:
  development:
    cmds:
      - go run . -config=./config.yml
  build:
    cmds:
      - CGO_ENABLED=0 go build -v -o bin/vaulguard{{.exeExt}} .
  test:
    cmds:
      - go test ./...
  docker-test:
    cmds:
      - docker-compose run  --use-aliases -d mongo
      - docker-compose run  --use-aliases -d db
      - docker run -it --rm --network vaulguard_vaulguard -e GOPATH=/go -e VAULGUARD_MONGO_TESTING="mongodb://mongo:27017/" -v {{.PWD}}:/vaulguard -v vaulguard_go:/go/pkg -w /vaulguard golang:1.15 go test ./...
      - docker ps | grep -P "vaulguard_\w+_run_[a-fA-F0-9]+" | awk '{ print $1 }' | xargs -I '{}' docker rm -f '{}'
  build-image:
    cmds:
      - docker build .
  docker-dev:
    cmds:
      - docker-compose up -d --build
  format:
    cmds:
      - go fmt ./...
  vet:
    cmds:
      - go vet ./...
